### ISSUE TITLE
incorrect #include paths

### ISSUE THREAD

**Issue by tdjastrzebski** [STMicroelectronics/32f769idiscovery-bsp#1]
Hi ST!
I am really glad to see board drivers are finally split into modules and placed on Github. It is a highly appreciated, long awaited effort in the right direction and mindset change.
What probably should be improved now is consistency.
Example: in [stm32f769i_discovery_audio.h](https://github.com/STMicroelectronics/32f769idiscovery-bsp/blob/main/stm32f769i_discovery_audio.h) file you have this line:  
```C++
#include "../Components/wm8994/wm8994.h"
```
which should be changed to:  
```C++
#include "stm32-wm8994/wm8994.h"
```
because **wm8994.h** header comes from [stm32-wm8994](https://github.com/STMicroelectronics/stm32-wm8994) module/libary and `Components/wm8994` folder exists nowhere.
`Components` folder is a legacy stuff and it should be removed as currently it only breaks consistency.  
I know the change I suggest needs to be reflected in the complete package for this board but this change has to be made.

**Comment by tdjastrzebski** [comment]
... and, btw, device drivers like `wm8994.h` and others should probably be added to this repo as Git submodules.  
This would allow you for basic dependency version control. It is not as sophisticated as npm or pip but it is probably 'good enough' 'low hanging fruit', way better than nothing.

**Comment by TOUNSTM** [comment]
Hello @tdjastrzebski,

As we should maintain compatibility with the delivered package the content of BSP component repositories should be kept aligned. It is thus up to user to update them.
Regarding your second request, unfortunately, there is no plan to deploy Git submodule for BSP components for the moment. we'll keep you informed.

Please allow me to close this issue. Thank you for your comprehension and thank you for your report.
