### ISSUE TITLE
Missing Fonts

### ISSUE THREAD

**Issue by tdjastrzebski** [STMicroelectronics/32f769idiscovery-bsp#2]
[stm32f769i_discovery_lcd.c](https://github.com/STMicroelectronics/32f769idiscovery-bsp/blob/main/stm32f769i_discovery_lcd.c) file contains these includes:
```C++
#include "../../../Utilities/Fonts/fonts.h"
#include "../../../Utilities/Fonts/font24.c"
#include "../../../Utilities/Fonts/font20.c"
#include "../../../Utilities/Fonts/font16.c"
#include "../../../Utilities/Fonts/font12.c"
#include "../../../Utilities/Fonts/font8.c"
```
[stm32f769i_discovery_lcd.h](https://github.com/STMicroelectronics/32f769idiscovery-bsp/blob/main/stm32f769i_discovery_lcd.h)  has:
```C++
#include "../../../Utilities/Fonts/fonts.h"
```
but `Fonts` are nowhere to be found.

Why do you include `*.c` files?! Even if `Files` folder is added from the complete package, this code results in "multiple definitions of..." error during linking stage because `fontxx.c` already includes `fonts.h`.  
Follow common good practice and Include header file(s) only.

**Comment by TOUNSTM** [comment]
Hello @tdjastrzebski,

In fact, it's the choice of our development team to work with this approach (making includes with .c files). Also, we use these files in our projects and we haven't detected any problems of this kind. In the latter case, could you provide the test case allowing to reproduce the failure?

Regarding the point for which you opened the issue, as it is irrelevant, allow me to close the issue. Anyway, if you ever become able to reproduce the faulty behavior, do not hesitate to recontact me. We could reopen this issue again.

Thank you for your comprehension and thank you again for your report. We look forward to hearing from you again.

With regards,
